### ISSUE TITLE
El procés de verificació de mail no funciona

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#11]
No puc verificar correu (no arriba cap correu), així que no hi ha forma d'entrar a fer proves amb un usuari empresa.

**Comment by andriusmp** [comment]
Ok, arreglat!

**Comment by andriusmp** [comment]
No sé què ha passat, però torna a fallar. Ara el que passa:
- Dono d'alta l'usuari (no des de l'admin)
- Faig clic a l'enllaç que m'arriba al correu per a verificar (ex: https://ineditencercla.pythonanywhere.com/user/verify_email/8b503f12-337a-4123-a12d-6aca24b12633)
- No em porta a la pantalla de canvi de contrasenya, si no al login (amb un missatge de verificació de mail correcta o algo així)
- Error d'autenticació quan intento entrar:
![image](https://user-images.githubusercontent.com/42779858/61211318-977e0300-a6ff-11e9-866e-3e96dad9576e.png)

**Comment by andriusmp** [comment]
Això segueix igual. Per poder crear un usuari cal:
1. Donar-se d'alta (posant una contrasenya) --> això els porta al login sense cap info de que han de validar el correu --> **cal afegir missatge**
2. Fer clic a l'enllaç que s'ha rebut al correu
3. Et porta a login, però diu inici de sessió no vàlid
4. Cal fer el procés de contrasenya oblidada

Aquest procés és massa complex

**Comment by codstar** [comment]
Ara ja mostra missatge quan es registra l'usuari.
La contrasenya que fiques inicialment ha de funcionar. Si pots, torna a provar el proces, perque he fet canvis.

**Comment by codstar** [comment]
Definitivament ara si esta resolt el tema de que la contrasenya no funcionara.

**Comment by andriusmp** [comment]
ok
