### ISSUE TITLE
Falten opcions de qüestionari per l'usuari empresa

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#16]
Falten dues funcionalitats:
- L'usuari empresa no té opció d'esborrar qüestionaris. Pels no enviats, l'hauria de tenir.
- No veig on està l'opció de duplicar qüestionaris

**Comment by andriusmp** [comment]
Ja es pot duplicar, però no esborrar

**Comment by codstar** [comment]
Solucionat en versió de desenvolupament, quan pugi la propera versió estarà disponible.
