### ISSUE TITLE
Els adjunts justificatius no es poden esborrar

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#18]
El botó d'esborrar no és clicable
![image](https://user-images.githubusercontent.com/42779858/61223258-a0c99880-a71c-11e9-926c-8337131bb98a.png)

**Comment by codstar** [comment]
Si es pot, fixat que es un checkbox que has de marcar.

**Comment by andriusmp** [comment]
Nico, ara no veig ni la creu:
![image](https://user-images.githubusercontent.com/42779858/61519419-2a72b200-aa0c-11e9-983a-9e7484835066.png)
En el seu moment, la creu la veia i la vaig marcar, però la paraula 'eliminar' no era un link, era un text pla (crec que s'havia colat alguna cosa, perquè de fet es mostrava un ] al final)

**Comment by codstar** [comment]
Les dos captures que mostres son de dos moments diferents. La primera que vas indicar es quan tornes a entrar a una pregunta que ja s'ha desat amb el fitxer adjunt. I es aquest cas al que em referia en que apareix un checkbox.
Si afegeixes un fitxer i encara no has desat la pregunta no es pot eliminar. Veré que puc fer en aquest cas.

**Comment by andriusmp** [comment]
Ah vale, entenc!!
No cal que ho modifiquis això doncs, ja està bé.
Però la part d'eliminar (quan ja està desada la pregunta) no és gaire intuïtiva. Costa molt entendre que per a que l'eliminació sigui efectiva cal canviar de pregunta...

**Comment by codstar** [comment]
Amb el checkbox el funcionament es coherent amb la resta de controls del formulari (els textos i la pregunta), es a dir, que només es desen les modificacions quan canvies de pregunta. Si fiquem un botó especific, que elimina el fitxer immediatament, es un comportament estrany i l'usuari pot pensar: per què s'ha esborrat el fitxer si no he desat la pregunta?, no creus? (i un altre problema es que es més fàcil fer un esborrat accidental)
Que penses?

**Comment by andriusmp** [comment]
Entenc el que dius, però com a usuari, és fàcil que triï un arxiu equivocat i el vulgui canviar. I no em donarà per pensar que si marco el checkbox, larxiu s'eliminarà quan es desi la pregunta (també perquè l'usuari no té consciència que el qüestionari es desa en el moment en el que canvia de pregunta).

Fem una cosa, si és fàcil posar un botó específic, fem-ho. Si no, deixem-ho així.

**Comment by andriusmp** [comment]
ok
