### ISSUE TITLE
Falten funcionalitats rànquing

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#32]
1. Exportar
2. Gràfica comparativa

**Comment by andriusmp** [comment]
L'exportació dona un internal error:
![image](https://user-images.githubusercontent.com/42779858/61616017-a9175b80-ac67-11e9-9bba-00d1b848a03f.png)

**Comment by codstar** [comment]
Solucionat

**Comment by andriusmp** [comment]
ok
