### ISSUE TITLE
Usuari administrador > Obligatorietat de crear-li una empresa

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#37]
No té gaire sentit que l'usuari administrador hagi de tenir obligatòriament una empresa associada. Seria fàcil que, quan es marca aquesta opció, els camps d'empresa no siguin obligatoris?

**Comment by codstar** [comment]
Ja, ho entenc perfectament.
El problema es que complica una mica més la implementació perque aleshores hi ha usuaris de dos tipus, amb dos comportaments diferents. Si un usuari no te empresa no pot tinde plantilles ni questionaris associats i aleshores un usuari administrador no podria fer proves (amb el seu usuari) de crear enquestes. 
Està clar que si no tinguerem un pressupost tan limitat es podrien diferenciar sense problemes, el problema sempre es el pressupost. ;)

**Comment by andriusmp** [comment]
D'acord, entesos! Deixem-ho així doncs, tampoc és res greu!
