### ISSUE TITLE
Errors idioma pantalla resultats

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#38]
A la pantalla de resultats hi ha varios errors d'idioma:

1. Resultats y propostes de millora > Resultats **i** propostes de millora
2. Evaluació > **A**valuació
3. convocatoria > convocat**ò**ria 

![image](https://user-images.githubusercontent.com/42779858/61615411-3b1e6480-ac66-11e9-9207-760117129a02.png)

**Comment by codstar** [comment]
Corregit al servidor.

**Comment by andriusmp** [comment]
ok
