### ISSUE TITLE
Traducció login

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#39]
Les opcions de login només es tradueixen en alguns casos, i només si l'usuari està loggejat. Sense un usuari connectat, surten sempre en anglès, alguns usuaris no ho entendran. Podem deixar per defecte el català quan no hi hagi usuari connectat? (a tota la interfície: condicions legals, etc).
![image](https://user-images.githubusercontent.com/42779858/61616319-61dd9a80-ac68-11e9-856c-fc0654a74c49.png)

**Comment by codstar** [comment]
Jo si que ho veig traduït. 
Crec que tu ho veus en anglés perque el navigador t'esta mostrant una versiò antiga de la cache:
- prova a actualitzar la pàgina amb la tecla "Shift" ("Mayús") pulsada
Em pots confirmar que si ho veus en l'idioma correcte?

D'altra banda, el idioma utilitzat per a mostrar la pantalla inicial, quan l'usuari no esta loggejat, es el que tinguis configurat a les opcions del teu navigador.

**Comment by andriusmp** [comment]
Perfecte, tenies raó! 
L'únic és que en català li falta una 'n' a Desconnectar
![image](https://user-images.githubusercontent.com/42779858/61625490-2a2c1e00-ac7b-11e9-9daa-1b70cbcbc26b.png)

**Comment by codstar** [comment]
Corregit!

**Comment by andriusmp** [comment]
ok
