### ISSUE TITLE
Dubtes sobre gestió d'usuaris

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#4]
1) Si entro amb un usuari administrador (inedit@localhost), perquè no puc esborrar alguns usuaris?
![image](https://user-images.githubusercontent.com/42779858/61117609-276d4400-a497-11e9-828a-4685cd13826a.png)
2) Com puc crear un altre usuari administrador? Quan creo usuari no hi ha possibilitat de marcar cap opció
3) Hi ha barreja d'idiomes en els missatges ('Please confirm deletion'). Entenc que aquests són els de sistema: es pot adaptar a l'idioma que estigui seleccionat a la interface?
![image](https://user-images.githubusercontent.com/42779858/61119216-9ef0a280-a49a-11e9-8e37-c487db63bc62.png)
![image](https://user-images.githubusercontent.com/42779858/61119642-92207e80-a49b-11e9-92d6-1baf967dbdaa.png)
4)

**Comment by codstar** [comment]
Els usuaris que no pots borrar son usuaris especials per desenvolupament.

**Comment by andriusmp** [comment]
ok
