### ISSUE TITLE
Verificació del correu electrònic durant la creació d'un usuari

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/enCErcla-Nico#7]
Aquesta funcionalitat no la teníem activada. Em sembla ok, però l'usuari no entendrà perquè es registra i torna a la pantalla d'inici sense cap missatge que li indiqui que ha de verificar el seu correu.
Un altra cosa, què passa amb els usuaris que no han verificat correu? Es donen d'alta igualment al llistat d'usuaris que se li mostra a l'administrador? Hi ha alguna manera que l'administrador sàpiga quins no estan donats d'alta?

**Comment by codstar** [comment]
- ara es mostra un missatge a l'usuari quan es registra de que li hem enviat un email
- si, encara que l'usuari no hagi verificat el seu correu, l'usuari està creat, pero ell no podrà fer login fins que verifique el correu
- si, afegiré una columna per a veure si l'usuari ha verificat el correu

**Comment by andriusmp** [comment]
Ok
